script: 
  - gcc -o tls-parser src/tls_parser.* -Wall
  - ./tls-parser examples/valid/TLSv1.2/Certificate
  - ./tls-parser examples/valid/TLSv1.2/ServerHelloDone
  - ./tls-parser examples/valid/TLSv1.0/ClientHello
  - ./tls-parser examples/valid/TLSv1.2/ServerHello
